### ISSUE TITLE
Can you add more Malayalam channels?

### ISSUE THREAD

**Issue by Manipulativemachan** [naveenland4/YouTube_to_m3u#11]
Can you add more channels to this list?

https://www.youtube.com/watch?v=S00GfgVAjls&ab_channel=KeralaVisionNews24x7

https://www.youtube.com/watch?v=0hA-si6w3zc&ab_channel=ShekinahNewsLive

https://www.youtube.com/watch?v=eaTCyjv0SOk&ab_channel=REPORTERLIVE

**Comment by naveenland4** [comment]
Added bro... Except Shekinah News. It is HLS thus m3u creation is not possible.

Thanks.

**Comment by Manipulativemachan** [comment]
https://www.youtube.com/watch?v=9B5zO7BHrlE&ab_channel=Youtalk

Can I keep adding it here? Added one more that I found now.

**Comment by naveenland4** [comment]
Added this one. Link will be available in the next batch run. Thanks.
