### ISSUE TITLE
Add following malayalam channels

### ISSUE THREAD

**Issue by Manipulativemachan** [naveenland4/YouTube_to_m3u#14]
Shalom Tv
https://www.youtube.com/watch?v=xpBJo6xmtnA&ab_channel=ShalomPrayer

Goodness TV
https://www.youtube.com/watch?v=wVV7cQTnc-E&ab_channel=GOODNESSNEWS

Powervision
https://www.youtube.com/watch?v=L42NP9a8paw&ab_channel=POWERVISIONTV

**Comment by naveenland4** [comment]
Added
