### ISSUE TITLE
Issues with multiple Lives at same time

### ISSUE THREAD

**Issue by elavarasan-sr** [naveenland4/YouTube_to_m3u#5]
When there is Two lives in a channel "**https://www.youtube.com/channel/CHANNEL_ID/live**" this url gives the second live stream url. As today ploimer news live streamed TN Assembly stream it replased the First news stream.

For example WION news channel mostly have more than one live stream but while genrating the m3u8 links we will only get the latest live link not the news live link.

**Comment by naveenland4** [comment]
Hello Elavarasan - The Script is based on the live links. Earlier i have been updating the direct link for each live channels. But few of the channels are changing their live links very often. So i have placed the Youtube Channel links to generate the m3u8 link from the latest live video links.

**Comment by elavarasan-sr** [comment]
Hi Naveen, Why can't go for the official yotube api which will give the list of all current live streams going on the channel and we can get the video id of the all lives too. Then with the induvidual video id's of lives we can grab the m3u8 of all streams.

https://www.googleapis.com/youtube/v3/search?part=snippet&channelId=[CHANNEL-ID]&eventType=live&type=video&key=[YOUR-API-KEY]
