### ISSUE TITLE
Need help 

### ISSUE THREAD

**Issue by Yumega** [naveenland4/YouTube_to_m3u#7]
Dear naveenland4

How to make my m3u list to be updated automatically ?

https://github.com/Yumega/YouTube_to_m3u 

it never update with my own youtube_channel_info.txt

**Comment by chikebum** [comment]
> Dear naveenland4
> 
> How to make my m3u list to be updated automatically ?
> 
> https://github.com/Yumega/YouTube_to_m3u
> 
> it never update with my own youtube_channel_info.txt

did you manage how to fix it ?

**Comment by Yumega** [comment]
> > Dear naveenland4
> > How to make my m3u list to be updated automatically ?
> > https://github.com/Yumega/YouTube_to_m3u
> > it never update with my own youtube_channel_info.txt
> 
> did you manage how to fix it ?

Yes, has fixed

**Comment by chikebum** [comment]
> > > Dear naveenland4
> > > How to make my m3u list to be updated automatically ?
> > > https://github.com/Yumega/YouTube_to_m3u
> > > it never update with my own youtube_channel_info.txt
> > 
> > 
> > did you manage how to fix it ?
> 
> Yes, has fixed

how ? my m3u_Generator.yml always fail

**Comment by Yumega** [comment]
> > > > Dear naveenland4
> > > > How to make my m3u list to be updated automatically ?
> > > > https://github.com/Yumega/YouTube_to_m3u
> > > > it never update with my own youtube_channel_info.txt
> > > 
> > > 
> > > did you manage how to fix it ?
> > 
> > 
> > Yes, has fixed
> 
> how ? my m3u_Generator.yml always fail

just click Actions tab ,then click  M3U generator ,then click run workflow, then wait M3U generator

**Comment by chikebum** [comment]
ok thanks

> > > > > Dear naveenland4
> > > > > How to make my m3u list to be updated automatically ?
> > > > > https://github.com/Yumega/YouTube_to_m3u
> > > > > it never update with my own youtube_channel_info.txt
> > > > 
> > > > 
> > > > did you manage how to fix it ?
> > > 
> > > 
> > > Yes, has fixed
> > 
> > 
> > how ? my m3u_Generator.yml always fail
> 
> just click Actions tab ,then click M3U generator ,then click run workflow, then wait M3U generator
